induction b with k h,
rw add_zero, rw mul_zero, rw add_zero,
refl,
rw mul_succ,
rw succ_eq_add_one,
rw ← add_assoc,
rw ← add_assoc (t * a) (t*k) t, rw ← h,
rw ← mul_succ t (a + k),
rw ← succ_eq_add_one,
refl,
